### PR TITLE
Fix/cs 44032

### PR DESCRIPTION
**Pull request by abhinav-from-contentstack**
- handled fragment case
- bumped version to 1.1.1

### CODE REVIEW

**Review by sunil-lakshman — COMMENTED** [review]
@abhinav-from-contentstack Delete only sast-scan.yml & secrets-scan.yml file and keep back the sca-scan file.

Update the changelog file as well

**Comment by abhinav-from-contentstack** [comment]
Hi @sunil-lakshman , @aravindbuilt has suggested to delete these workflows.
cc : @netrajpatel

**Review by ishaileshmishra — APPROVED** [review]
approved

**Comment by ishaileshmishra** [comment]
tests are missing @abhinav-from-contentstack , take care of tests as well, rest LGTM

**Comment by abhinav-from-contentstack** [comment]
tests will be added as part of another ticket, @ishaileshmishra 
cc : @netrajpatel

**Pull request merged**
